/*GET THE DATASET TO LIBRARIES & PRINT THE DATA*/
FILENAME REFFILE '/home/u59388928/sasuser.v94/Listings.xlsx';

PROC IMPORT DATAFILE=REFFILE
	DBMS=XLSX
	OUT=WORK.LISTINGS;
	GETNAMES=YES;
RUN;

PROC CONTENTS DATA=WORK.LISTINGS; 
RUN;

PROC PRINT DATA=LISTINGS NOOBS;
RUN;




/*HANDLE INCOMPLETE DATA*/
/*AFTER CHECK ALL FREQ TABLE FOR EVERY ATTRIBUTES, ONLY NAME HAS MISSING DATA*/
PROC SORT DATA= LISTINGS OUT=SORT_LISTINGS;
	BY Name;
RUN;

DATA LISTINGS_1;
SET SORT_LISTINGS;
IF Name = ' ' THEN DELETE;
IF Name = '.' THEN DELETE;
RUN;




/*HANDLE NOISY DATA*/
/*NOISY DATA IN HOST NAME, NAME, ROOM_TYPE, PRICE*/
/*REMOVE NOISY DATA IN HOST NAME*/
PROC SORT DATA= LISTINGS_1 OUT=SORT_LISTINGS_1;
	BY 'Host Name'n;
RUN;

PROC PRINT DATA=SORT_LISTINGS_1 NOOBS;
RUN;

DATA LISTINGS_2;
SET SORT_LISTINGS_1;
IF _n_ = 1 THEN DELETE;
IF _n_ GE 10 and _n_ LE 117 THEN DELETE;
RUN;




/*REMOVE NOISY DATA IN NAME*/
PROC SORT DATA= LISTINGS_2 OUT=SORT_LISTINGS_2;
	BY Name;
RUN;

PROC PRINT DATA=SORT_LISTINGS_2 NOOBS;
RUN;

DATA LISTINGS_3;
SET SORT_LISTINGS_2;
Name = COMPRESS(Name,'?');
RUN;



DATA LISTINGS_4;
SET LISTINGS_3;
IF Name = '' THEN DELETE;
IF Name = '.' THEN DELETE;
IF Name = '!' THEN DELETE;
IF Name = '#' THEN DELETE;
IF Name = '()' THEN DELETE;
IF Name = '+++++' THEN DELETE;
IF Name = ',' THEN DELETE;
IF Name = ',,' THEN DELETE;
IF Name = ',,,' THEN DELETE;
IF Name = '#NAME' THEN DELETE;
IF Name = '-' THEN DELETE;
RUN;



/*HANDLING NOISY & INCONSISTENT DATA IN ROOM_TYPE*/
/*THIS CODE IN LINE 87- 93 ONLY TO CHECK*/
DATA TOCHECK;   
SET LISTINGS_4;
IF 'Room Type'n = '.' THEN OUTPUT TOCHECK;
RUN;

PROC PRINT DATA=TOCHECK NOOBS; 
RUN;

DATA LISTINGS_5;
SET LISTINGS_4;
IF 'Room Type'n = '.' AND Price > 0 AND Price <35 THEN 'Room Type'n = 'Shared room';
IF 'Room Type'n = '.' AND Price >= 35 AND Price <= 120 THEN 'Room Type'n = 'Private room';
IF 'Room Type'n = '.' AND Price > 120 THEN 'Room Type'n = 'Entire home/apt';
IF 'Room Type'n = 'Entire home |apt' THEN 'Room Type'n = 'Entire home/apt';
RUN;



/*HANDLING NOISY DATA IN PRICE*/
PROC SORT DATA=LISTINGS_5 OUT=SORT_LISTINGS_3;
	BY 'Room Type'n;
RUN;

PROC MEANS DATA=SORT_LISTINGS_3 CHARTYPE MEAN MEDIAN VARDEF=df Q1 Q3 QRANGE 
		QMETHOD=OS;
	VAR Price;
	BY 'Room Type'n;
	OUTPUT OUT =PRICE_STAT MEAN(PRICE)=Q1(PRICE)=Q3(PRICE)=QRANGE(PRICE) = /AUTONAME;
RUN;

DATA OUTLIER;
SET PRICE_STAT;
LB = PRICE_Q1 - (1.5*PRICE_QRANGE);
UB = PRICE_Q3 + (1.5*PRICE_QRANGE);
RUN;

PROC PRINT DATA = OUTLIER;
RUN;

DATA LISTINGS_6;
SET LISTINGS_5;
IF Price = 0 THEN DELETE;
IF 'Room Type'n = 'Entire home/apt' AND Price > 448.5 THEN Price = 227;
IF 'Room Type'n = 'Private room' AND Price > 175 THEN Price = 108;
IF 'Room Type'n = 'Shared room' AND Price > 86 THEN Price = 65;
RUN;

/*SORT DATA FOR FINAL DATASET*/
PROC SORT DATA= LISTINGS_6 OUT=FINAL_LISTINGS;
	BY _ALL_;
RUN;

